name: 'MapFlow Smoke Test'
description: 'Run smoke tests on a Docker image'

inputs:
  image:
    description: 'Docker image to test'
    required: true
  port:
    description: 'Port to expose'
    required: false
    default: '39000'

runs:
  using: 'composite'
  steps:
    - name: Smoke test container
      shell: bash
      run: |
        set -euo pipefail

        port="${{ inputs.port }}"
        data_dir="${RUNNER_TEMP}/mapflow-data"
        uploads_dir="${RUNNER_TEMP}/mapflow-uploads"
        mkdir -p "$data_dir" "$uploads_dir"

        cid=""
        cleanup() {
          if [ -n "$cid" ]; then
            docker logs --tail 200 "$cid" || true
            docker stop "$cid" >/dev/null 2>&1 || true
          fi
        }
        trap cleanup EXIT

        cid=$(docker run -d --rm \
          -p "${port}:3000" \
          -e PORT=3000 \
          -e DB_PATH=/app/data/mapflow.duckdb \
          -e UPLOAD_DIR=/app/uploads \
          -v "${data_dir}:/app/data" \
          -v "${uploads_dir}:/app/uploads" \
          "${{ inputs.image }}")

        echo "Waiting for server to be ready..."
        for i in $(seq 1 120); do
          if curl -fsS "http://127.0.0.1:${port}/api/files" >/dev/null; then
            echo "Server is ready after $((i/2)) seconds"
            break
          fi
          sleep 0.5
          if [ "$i" = "120" ]; then
            echo "server did not become ready" >&2
            exit 1
          fi
        done

        curl -fsS "http://127.0.0.1:${port}/" >/dev/null

        upload_resp=$(curl -fsS -F "file=@frontend/tests/fixtures/sample.geojson" "http://127.0.0.1:${port}/api/uploads")
        id=$(python3 -c 'import json,sys; print(json.loads(sys.stdin.read())["id"])' <<<"$upload_resp")

        for i in $(seq 1 120); do
          st=$(curl -fsS "http://127.0.0.1:${port}/api/files" | python3 -c 'import json,sys; id=sys.argv[1]; items=json.load(sys.stdin); print(next((it.get("status","") for it in items if it.get("id")==id), ""))' "$id")
          if [ "$st" = "ready" ]; then
            break
          fi
          if [ "$st" = "failed" ]; then
            echo "upload processing failed" >&2
            exit 1
          fi
          sleep 0.5
          if [ "$i" = "120" ]; then
            echo "timeout waiting for ready" >&2
            exit 1
          fi
        done

        curl -fsS "http://127.0.0.1:${port}/api/files/${id}/preview" >/dev/null

        curl -fsS -o /tmp/mapflow_smoke_tile.mvt "http://127.0.0.1:${port}/api/files/${id}/tiles/0/0/0"
        python3 - <<'PY'
        import base64, hashlib, os, sys
        testdata_path = os.path.join(os.environ['GITHUB_WORKSPACE'], 'testdata/smoke/expected_sample_z0_x0_y0.mvt.base64')
        expected_b64 = open(testdata_path,'r',encoding='ascii').read().strip()
        expected = base64.b64decode(expected_b64)
        got = open('/tmp/mapflow_smoke_tile.mvt','rb').read()
        if got != expected:
          print('tile mismatch')
          print('expected_sha256', hashlib.sha256(expected).hexdigest())
          print('got_sha256', hashlib.sha256(got).hexdigest())
          raise SystemExit(1)
        print('tile ok sha256', hashlib.sha256(got).hexdigest())
        PY
